quests={        "List of Final Fantasy XIV quests/Seventh Umbral Era",
        "List of Final Fantasy XIV quests/Seventh Astral Era",
        "List of Final Fantasy XIV quests/Heavensward",
        "List of Final Fantasy XIV quests/Dragonsong War",
        "List of Final Fantasy XIV quests/Post-Dragonsong War",
        "List of Final Fantasy XIV quests/Primal Quests",
        "List of Final Fantasy XIV quests/Bahamut Quests",
        "List of Final Fantasy XIV quests/Crystal Tower Quests",
        "List of Final Fantasy XIV quests/Alexander Quests",
        "List of Final Fantasy XIV quests/Shadow of Mhach",
        "List of Final Fantasy XIV quests/Main Quests",
        "List of Final Fantasy XIV quests/Daily Quests",
        "List of Final Fantasy XIV quests/Main Quests",
        "List of Final Fantasy XIV quests/Daily Quests",
        "List of Final Fantasy XIV quests/Main Quests",
        "List of Final Fantasy XIV quests/Daily Quests",
        "List of Final Fantasy XIV quests/Main Quests",
        "List of Final Fantasy XIV quests/Daily Quests",
        "List of Final Fantasy XIV quests/Daily Quests",
        "List of Final Fantasy XIV quests/Main Quests",
        "List of Final Fantasy XIV quests/Daily Quests",
        "List of Final Fantasy XIV quests/Main Quests",
        "List of Final Fantasy XIV quests/Daily Quests",
        "List of Final Fantasy XIV quests/Main Quests",
        "List of Final Fantasy XIV quests/Daily Quests",
        "List of Final Fantasy XIV quests/Hildibrand Quests",
        "List of Final Fantasy XIV quests/Further Hildibrand Adventures",
        "List of Final Fantasy XIV quests/Tales of the Dragonsong War",
        "List of Final Fantasy XIV quests/Wandering Minstrel Quests",
        "List of Final Fantasy XIV quests/Zodiac Weapons",
        "List of Final Fantasy XIV quests/Anima Weapons",
        "List of Final Fantasy XIV quests/Delivery Moogle Quests",
        "List of Final Fantasy XIV quests/Allied Beast Tribe Quests",
        "List of Final Fantasy XIV quests/",
        "List of Final Fantasy XIV quests/Doman Adventurers' Guild Quests",
        "List of Final Fantasy XIV quests/La Noscean Sidequests",
        "List of Final Fantasy XIV quests/Ul'dahn Sidequests",
        "List of Final Fantasy XIV quests/Coerthan Sidequests",
        "List of Final Fantasy XIV quests/Mor Dhonan Sidequests",
        "List of Final Fantasy XIV quests/Ishgardian Sidequests",
        "List of Final Fantasy XIV quests/Abalathian Sidequests",
        "List of Final Fantasy XIV quests/Dravanian Forelands Sidequests",
        "List of Final Fantasy XIV quests/Dravanian Hinterlands Sidequests",
        "List of Final Fantasy XIV quests/Churning Mists Sidequests",
        "List of Final Fantasy XIV quests/Idyllshire Sidequests",
        "List of Final Fantasy XIV quests/Gladiator Quests",
        "List of Final Fantasy XIV quests/Pugilist Quests",
        "List of Final Fantasy XIV quests/Marauder Quests",
        "List of Final Fantasy XIV quests/Lancer Quests",
        "List of Final Fantasy XIV quests/Archer Quests",
        "List of Final Fantasy XIV quests/Rogue Quests",
        "List of Final Fantasy XIV quests/Conjurer Quests",
        "List of Final Fantasy XIV quests/Thaumaturge Quests",
        "List of Final Fantasy XIV quests/Arcanist Quests",
        "List of Final Fantasy XIV quests/Blacksmith Quests",
        "List of Final Fantasy XIV quests/Armorer Quests",
        "List of Final Fantasy XIV quests/Goldsmith Quests",
        "List of Final Fantasy XIV quests/Leatherworker Quests",
        "List of Final Fantasy XIV quests/Weaver Quests",
        "List of Final Fantasy XIV quests/Alchemist Quests",
        "List of Final Fantasy XIV quests/Culinarian Quests",
        "List of Final Fantasy XIV quests/Miner Quests",
        "List of Final Fantasy XIV quests/Botanist Quests",
        "List of Final Fantasy XIV quests/Paladin Quests",
        "List of Final Fantasy XIV quests/Monk Quests",
        "List of Final Fantasy XIV quests/Warrior Quests",
        "List of Final Fantasy XIV quests/Dragoon Quests",
        "List of Final Fantasy XIV quests/Bard Quests",
        "List of Final Fantasy XIV quests/Ninja Quests",
        "List of Final Fantasy XIV quests/White Mage Quests",
        "List of Final Fantasy XIV quests/Black Mage Quests",
        "List of Final Fantasy XIV quests/Summoner Quests",
        "List of Final Fantasy XIV quests/Dark Knight Quests",
        "List of Final Fantasy XIV quests/Machinist Quests",
        "List of Final Fantasy XIV quests/Astrologian Quests",
        "List of Final Fantasy XIV quests/Maelstrom Quests",
        "List of Final Fantasy XIV quests/Order of the Twin Adder Quests",
        "List of Final Fantasy XIV quests/Immortal Flames Quests",
        "List of Final Fantasy XIV quests/Seasonal Events",
        "List of Final Fantasy XIV quests/Heavensturn Events",
        "List of Final Fantasy XIV quests/Eastern Duties",
        "List of Final Fantasy XIV quests/Little Ladies' Day Events",
        "List of Final Fantasy XIV quests/Egg Hunts",
        "List of Final Fantasy XIV quests/Gold Saucer Festivities",
        "List of Final Fantasy XIV quests/Moonfire Faire Events",
        "List of Final Fantasy XIV quests/Rising Events",
        "List of Final Fantasy XIV quests/All Saints' Wake Events",
        "List of Final Fantasy XIV quests/Starlight Celebration Events",
        "List of Final Fantasy XIV quests/Other Seasonal Events",
        "List of Final Fantasy XIV quests/Special Quests",
        "List of Final Fantasy XIV quests/Fisher Levequests",
        "List of Final Fantasy XIV quests/Battlecraft Levequests",
        "List of Final Fantasy XIV quests/Carpenter Levequests",
        "List of Final Fantasy XIV quests/Blacksmith Levequests",
        "List of Final Fantasy XIV quests/Armorer Levequests",
        "List of Final Fantasy XIV quests/Goldsmith Levequests",
        "List of Final Fantasy XIV quests/Leatherworker Levequests",
        "List of Final Fantasy XIV quests/Weaver Levequests",
        "List of Final Fantasy XIV quests/Alchemist Levequests",
        "List of Final Fantasy XIV quests/Miner Levequests",
        "List of Final Fantasy XIV quests/Botanist Levequests",
        "List of Final Fantasy XIV quests/Fisher Levequests",
        "List of Final Fantasy XIV quests/",
        "List of Final Fantasy XIV quests/",
        "List of Final Fantasy XIV quests/",
        "List of Final Fantasy XIV quests/Maelstrom Levequests",
        "List of Final Fantasy XIV quests/Order of the Twin Adder Levequests",
        "List of Final Fantasy XIV quests/Immortal Flames Levequests",
        "List of Final Fantasy XIV quests/Instanced Raids",
        "List of Final Fantasy XIV quests/Trials",
        "List of Final Fantasy XIV quests/Guildhests",
        "List of Final Fantasy XIV quests/Legacy Main Scenario Quests",
        "List of Final Fantasy XIV quests/Legacy Sidequests",
        "List of Final Fantasy XIV quests/Legacy Class Quests",
        "List of Final Fantasy XIV quests/Legacy Job Quests",
        "List of Final Fantasy XIV quests/Legacy Grand Company Quests",
},,
quests={        "List of Final Fantasy XIV quests/Seventh Umbral Era",
        "List of Final Fantasy XIV quests/Seventh Astral Era",
        "List of Final Fantasy XIV quests/Heavensward",
        "List of Final Fantasy XIV quests/Dragonsong War",
        "List of Final Fantasy XIV quests/Post-Dragonsong War",
        "List of Final Fantasy XIV quests/Primal Quests",
        "List of Final Fantasy XIV quests/Bahamut Quests",
        "List of Final Fantasy XIV quests/Crystal Tower Quests",
        "List of Final Fantasy XIV quests/Alexander Quests",
        "List of Final Fantasy XIV quests/Shadow of Mhach",
        "List of Final Fantasy XIV quests/Main Quests",
        "List of Final Fantasy XIV quests/Daily Quests",
        "List of Final Fantasy XIV quests/Main Quests",
        "List of Final Fantasy XIV quests/Daily Quests",
        "List of Final Fantasy XIV quests/Main Quests",
        "List of Final Fantasy XIV quests/Daily Quests",
        "List of Final Fantasy XIV quests/Main Quests",
        "List of Final Fantasy XIV quests/Daily Quests",
        "List of Final Fantasy XIV quests/Daily Quests",
        "List of Final Fantasy XIV quests/Main Quests",
        "List of Final Fantasy XIV quests/Daily Quests",
        "List of Final Fantasy XIV quests/Main Quests",
        "List of Final Fantasy XIV quests/Daily Quests",
        "List of Final Fantasy XIV quests/Main Quests",
        "List of Final Fantasy XIV quests/Daily Quests",
        "List of Final Fantasy XIV quests/Hildibrand Quests",
        "List of Final Fantasy XIV quests/Further Hildibrand Adventures",
        "List of Final Fantasy XIV quests/Tales of the Dragonsong War",
        "List of Final Fantasy XIV quests/Wandering Minstrel Quests",
        "List of Final Fantasy XIV quests/Zodiac Weapons",
        "List of Final Fantasy XIV quests/Anima Weapons",
        "List of Final Fantasy XIV quests/Delivery Moogle Quests",
        "List of Final Fantasy XIV quests/Allied Beast Tribe Quests",
        "List of Final Fantasy XIV quests/",
        "List of Final Fantasy XIV quests/Doman Adventurers' Guild Quests",
        "List of Final Fantasy XIV quests/La Noscean Sidequests",
        "List of Final Fantasy XIV quests/Ul'dahn Sidequests",
        "List of Final Fantasy XIV quests/Coerthan Sidequests",
        "List of Final Fantasy XIV quests/Mor Dhonan Sidequests",
        "List of Final Fantasy XIV quests/Ishgardian Sidequests",
        "List of Final Fantasy XIV quests/Abalathian Sidequests",
        "List of Final Fantasy XIV quests/Dravanian Forelands Sidequests",
        "List of Final Fantasy XIV quests/Dravanian Hinterlands Sidequests",
        "List of Final Fantasy XIV quests/Churning Mists Sidequests",
        "List of Final Fantasy XIV quests/Idyllshire Sidequests",
        "List of Final Fantasy XIV quests/Gladiator Quests",
        "List of Final Fantasy XIV quests/Pugilist Quests",
        "List of Final Fantasy XIV quests/Marauder Quests",
        "List of Final Fantasy XIV quests/Lancer Quests",
        "List of Final Fantasy XIV quests/Archer Quests",
        "List of Final Fantasy XIV quests/Rogue Quests",
        "List of Final Fantasy XIV quests/Conjurer Quests",
        "List of Final Fantasy XIV quests/Thaumaturge Quests",
        "List of Final Fantasy XIV quests/Arcanist Quests",
        "List of Final Fantasy XIV quests/Blacksmith Quests",
        "List of Final Fantasy XIV quests/Armorer Quests",
        "List of Final Fantasy XIV quests/Goldsmith Quests",
        "List of Final Fantasy XIV quests/Leatherworker Quests",
        "List of Final Fantasy XIV quests/Weaver Quests",
        "List of Final Fantasy XIV quests/Alchemist Quests",
        "List of Final Fantasy XIV quests/Culinarian Quests",
        "List of Final Fantasy XIV quests/Miner Quests",
        "List of Final Fantasy XIV quests/Botanist Quests",
        "List of Final Fantasy XIV quests/Paladin Quests",
        "List of Final Fantasy XIV quests/Monk Quests",
        "List of Final Fantasy XIV quests/Warrior Quests",
        "List of Final Fantasy XIV quests/Dragoon Quests",
        "List of Final Fantasy XIV quests/Bard Quests",
        "List of Final Fantasy XIV quests/Ninja Quests",
        "List of Final Fantasy XIV quests/White Mage Quests",
        "List of Final Fantasy XIV quests/Black Mage Quests",
        "List of Final Fantasy XIV quests/Summoner Quests",
        "List of Final Fantasy XIV quests/Dark Knight Quests",
        "List of Final Fantasy XIV quests/Machinist Quests",
        "List of Final Fantasy XIV quests/Astrologian Quests",
        "List of Final Fantasy XIV quests/Maelstrom Quests",
        "List of Final Fantasy XIV quests/Order of the Twin Adder Quests",
        "List of Final Fantasy XIV quests/Immortal Flames Quests",
        "List of Final Fantasy XIV quests/Seasonal Events",
        "List of Final Fantasy XIV quests/Heavensturn Events",
        "List of Final Fantasy XIV quests/Eastern Duties",
        "List of Final Fantasy XIV quests/Little Ladies' Day Events",
        "List of Final Fantasy XIV quests/Egg Hunts",
        "List of Final Fantasy XIV quests/Gold Saucer Festivities",
        "List of Final Fantasy XIV quests/Moonfire Faire Events",
        "List of Final Fantasy XIV quests/Rising Events",
        "List of Final Fantasy XIV quests/All Saints' Wake Events",
        "List of Final Fantasy XIV quests/Starlight Celebration Events",
        "List of Final Fantasy XIV quests/Other Seasonal Events",
        "List of Final Fantasy XIV quests/Special Quests",
        "List of Final Fantasy XIV quests/Fisher Levequests",
        "List of Final Fantasy XIV quests/Battlecraft Levequests",
        "List of Final Fantasy XIV quests/Carpenter Levequests",
        "List of Final Fantasy XIV quests/Blacksmith Levequests",
        "List of Final Fantasy XIV quests/Armorer Levequests",
        "List of Final Fantasy XIV quests/Goldsmith Levequests",
        "List of Final Fantasy XIV quests/Leatherworker Levequests",
        "List of Final Fantasy XIV quests/Weaver Levequests",
        "List of Final Fantasy XIV quests/Alchemist Levequests",
        "List of Final Fantasy XIV quests/Miner Levequests",
        "List of Final Fantasy XIV quests/Botanist Levequests",
        "List of Final Fantasy XIV quests/Fisher Levequests",
        "List of Final Fantasy XIV quests/",
        "List of Final Fantasy XIV quests/",
        "List of Final Fantasy XIV quests/",
        "List of Final Fantasy XIV quests/Maelstrom Levequests",
        "List of Final Fantasy XIV quests/Order of the Twin Adder Levequests",
        "List of Final Fantasy XIV quests/Immortal Flames Levequests",
        "List of Final Fantasy XIV quests/Instanced Raids",
        "List of Final Fantasy XIV quests/Trials",
        "List of Final Fantasy XIV quests/Guildhests",
        "List of Final Fantasy XIV quests/Legacy Main Scenario Quests",
        "List of Final Fantasy XIV quests/Legacy Sidequests",
        "List of Final Fantasy XIV quests/Legacy Class Quests",
        "List of Final Fantasy XIV quests/Legacy Job Quests",
        "List of Final Fantasy XIV quests/Legacy Grand Company Quests",
},,
items={        "List of Final Fantasy XIV items/Pugilist's Arm",
        "List of Final Fantasy XIV items/Gladiator's Arm",
        "List of Final Fantasy XIV items/Marauder's Arm",
        "List of Final Fantasy XIV items/Archer's Arm",
        "List of Final Fantasy XIV items/Lancer's Arm",
        "List of Final Fantasy XIV items/Onehanded Thaumaturge's Arm",
        "List of Final Fantasy XIV items/Twohanded Thaumaturge's Arm",
        "List of Final Fantasy XIV items/Onehanded Conjurer's Arm",
        "List of Final Fantasy XIV items/Twohanded Conjurer's Arm",
        "List of Final Fantasy XIV items/Shield",
        "List of Final Fantasy XIV items/Carpenter's Primary Tool",
        "List of Final Fantasy XIV items/Carpenter's Secondary Tool",
        "List of Final Fantasy XIV items/Blacksmith's Primary Tool",
        "List of Final Fantasy XIV items/Blacksmith's Secondary Tool",
        "List of Final Fantasy XIV items/Armorer's Primary Tool",
        "List of Final Fantasy XIV items/Armorer's Secondary Tool",
        "List of Final Fantasy XIV items/Goldsmith's Primary Tool",
        "List of Final Fantasy XIV items/Goldsmith's Secondary Tool",
        "List of Final Fantasy XIV items/Leatherworker's Secondary Tool",
        "List of Final Fantasy XIV items/Weaver's Primary Tool",
        "List of Final Fantasy XIV items/Weaver's Secondary Tool",
        "List of Final Fantasy XIV items/Alchemist's Primary Tool",
        "List of Final Fantasy XIV items/Alchemist's Secondary Tool",
        "List of Final Fantasy XIV items/Culinarian's Primary Tool",
        "List of Final Fantasy XIV items/Culinarian's Secondary Tool",
        "List of Final Fantasy XIV items/Miner's Primary Tool",
        "List of Final Fantasy XIV items/Miner's Secondary Tool",
        "List of Final Fantasy XIV items/Botanist's Secondary Tool",
        "List of Final Fantasy XIV items/Fisher's Primary Tool",
        "List of Final Fantasy XIV items/Fishing Tackle",
        "List of Final Fantasy XIV items/Head",
        "List of Final Fantasy XIV items/Body",
        "List of Final Fantasy XIV items/Legs",
        "List of Final Fantasy XIV items/Hands",
        "List of Final Fantasy XIV items/Feet",
        "List of Final Fantasy XIV items/Waist",
        "List of Final Fantasy XIV items/Earrings",
        "List of Final Fantasy XIV items/Bracelets",
        "List of Final Fantasy XIV items/Ring",
        "List of Final Fantasy XIV items/Medicine",
        "List of Final Fantasy XIV items/Ingredient",
        "List of Final Fantasy XIV items/Meal",
        "List of Final Fantasy XIV items/Seafood",
        "List of Final Fantasy XIV items/Stone",
        "List of Final Fantasy XIV items/Metal",
        "List of Final Fantasy XIV items/Cloth",
        "List of Final Fantasy XIV items/Leather",
        "List of Final Fantasy XIV items/Bone",
        "List of Final Fantasy XIV items/Reagent",
        "List of Final Fantasy XIV items/Dye",
        "List of Final Fantasy XIV items/Part",
        "List of Final Fantasy XIV items/Furnishing",
        "List of Final Fantasy XIV items/Materia",
        "List of Final Fantasy XIV items/Crystal",
        "List of Final Fantasy XIV items/Miscellany",
        "List of Final Fantasy XIV items/Soul Crystal",
        "List of Final Fantasy XIV items/Other",
        "List of Final Fantasy XIV items/Construction Permit",
        "List of Final Fantasy XIV items/Roof",
        "List of Final Fantasy XIV items/Exterior Wall",
        "List of Final Fantasy XIV items/Window",
        "List of Final Fantasy XIV items/Door",
        "List of Final Fantasy XIV items/Roof Decoration",
        "List of Final Fantasy XIV items/Placard",
        "List of Final Fantasy XIV items/Fence",
        "List of Final Fantasy XIV items/Interior Wall",
        "List of Final Fantasy XIV items/Flooring",
        "List of Final Fantasy XIV items/Ceiling Light",
        "List of Final Fantasy XIV items/Outdoor Furnishing",
        "List of Final Fantasy XIV items/Table",
        "List of Final Fantasy XIV items/Tabletop",
        "List of Final Fantasy XIV items/Wall-mounted",
        "List of Final Fantasy XIV items/Minion",
        "List of Final Fantasy XIV items/Gardening",
        "List of Final Fantasy XIV items/Demimateria",
        "List of Final Fantasy XIV items/Rogue's Arm",
        "List of Final Fantasy XIV items/Seasonal Miscellany",
        "List of Final Fantasy XIV items/Triple Triad Card",
        "List of Final Fantasy XIV items/Dark Knight's Arm",
        "List of Final Fantasy XIV items/Machinist's Arm",
        "List of Final Fantasy XIV items/Astrologian's Arm",
        "List of Final Fantasy XIV items/Airship Rigging",
        "List of Final Fantasy XIV items/Airship Aftcastle",
        "List of Final Fantasy XIV items/Airship Forecastle",
        "List of Final Fantasy XIV items/Orchestrion Roll",
        "List of Final Fantasy XIV items/",
        "List of Final Fantasy XIV items/",
        "List of Final Fantasy XIV items/",
        "List of Final Fantasy XIV items/",
        "List of Final Fantasy XIV items/",
},,
